- id: 10.1109/TII.2022.3200598
  type: paper
  date: 2023-04-1
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/9424/10081096/9864249/seok9-3200598-large.gif
  buttons:
    - type: website
      link: https://ieeexplore.ieee.org/abstract/document/9864249
  tags:
    - Digital twin
    - Veriifcation
    - time Petri net

- id: 10.1109/ISPACS57703.2022.10082830
- id: https://doi.org/10.1145/3518997.3531024
  image: https://www.google.com/url?sa=i&url=https%3A%2F%2Fsigsim.acm.org%2Fconf%2Fpads%2F2023%2F&psig=AOvVaw2PPRyI3LA9jcQ1yYAqZi7q&ust=1683921190232000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCMD097SF7v4CFQAAAAAdAAAAABAE

