
- id: 10.1016/j.jpdc.2024.104968
  date: 2024-12-1
  image: images/Publications/jpdc.jpg

- id: 10.1007/s12652-018-0943-8
  date: 2024-2-1
  image: https://media.springernature.com/w316/springer-static/cover-hires/journal/12652?as=webp

- id: 10.1145/3646549
  date: 2024-2-17
  image: images/Publications/tomacs_icon.jpeg

- id: 10.1109/ACCESS.2023.3337832
  date: 2023-11-30
  image: images/Publications/ieee_access.jpeg

- id: 10.1109/ACCESS.2023.3317283
  date: 2023-9-23
  image: images/Publications/ieee_access.jpeg

- id: 10.1145/3573900.3591112
  image: images/Publications/pads_icon.png

- id: 10.1109/TII.2022.3200598
  date: 2023-04-1
  image: https://www.ieee-ies.org/images/files/tii/tii-cover.png?v=2021

- id: 10.1109/ISPACS57703.2022.10082830
  image: images/Publications/ieee_icon.png

- id: 10.1145/3518997.3531024
  image: images/Publications/pads_icon.png

- id: 10.1145/3518997.3531024
  image: images/Publications/pads_icon.png

- id: https://dx.doi.org/10.2139/ssrn.4072423

- id: 10.1109/IPDPSW52791.2021.00015
  image: images/Publications/ipdps_2022_icon.png

- id: 10.1587/transele.2020LHP0001
  image: images/Publications/ieice_icon.png

- id: 10.1109/ACCESS.2021.3073618
  image: images/Publications/access_mmdc.png

- id: 10.3745/JIPS.01.0064
  image: http://koreascience.or.kr/journal/E1JBB0/v16n6/cover/thumb.image

- id: 10.1109/ACCESS.2020.3022275
  image: images/Publications/access_hi.png

- id: 10.1145/3384441.3395982
  image: images/Publications/pads_icon.png

- id: 10.22360/SpringSim.2020.TMS.005
  image: images/Publications/scs20.jpeg
  authors:
    - Chao Zhang
    - Hessam S. Sarjoughian
    - Moon Gi Seok

- id: 10.1109/COOLCHIPS49199.2020.9097638
  image: images/Publications/coolchip_icon.png

- id: 10.3745/JIPS.01.0060

- id: 10.1109/ACCESS.2019.2962253
  image: images/Publications/access_noc.png


- id: 10.1145/3287624.3287648
  image: images/Publications/aspdac_icon.png

- id: 10.1007/978-981-13-2853-4_5
  image: https://media.springernature.com/w316/springer-static/cover-hires/book/978-981-13-2853-4?as=webp

- id: 10.1007/978-981-10-7605-3_121
  image: https://media.springernature.com/w316/springer-static/cover-hires/book/978-981-10-7605-3?as=webp

- id: 10.1166/asl.2017.8601
  image: https://www.ingentaconnect.com/images/journal-logos/asp/asl.gif


- id: 10.1109/TVLSI.2016.2594948
  image: https://ieee-cas.org/files/ieeecass/styles/responsive_3_4_1280w/public/images/publications/TVLSI-reduced.jpg.webp?itok=-4gkf7wU


- id: 10.1109/MCSE.2016.76
  image: images/Publications/cise_icon.png

- id: 10.1587/elex.13.20160808
  image: images/Publications/ieice_icon.png

- id: 10.1504/IJSPM.2015.070462

- id: 10.1109/VLSI-SoC.2014.7004185
  image: images/Publications/IFIP_VLSISOC_logo.png

- id: 10.1177/1548512910389483
  authors:
    - Jeong Hee Hong
    - Kyung Min Seo
    - Moon Gi Seok
    - Tag Gon Kim



